apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-18T07:32:57Z"
  labels:
    app: nginx-app
  name: nginx-app
  namespace: default
  resourceVersion: "1087"
  uid: cf712ad7-47d2-4516-9df5-c672b07c9dd1
spec:
  clusterIP: 10.106.197.19
  clusterIPs:
  - 10.106.197.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31908
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
